# Generated by Django 3.0.6 on 2020-05-31 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predimages',
            old_name='images',
            new_name='image',
        ),
    ]
