export const GET_PREDICTIONS = "GET_PREDICTIONS";
export const DELETE_PREDICTION = "DELETE_PREDICTION";
export const ADD_PREDICTION = "ADD_PREDICTION";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";